"use client";
import { useState } from "react";
export function ListingActions({ listingId, slug, title, sellerId }: { listingId: string; slug: string; title: string; sellerId: string }) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [body, setBody] = useState(""); const [reason, setReason] = useState("spam"); const [notice, setNotice] = useState("");
  async function contact(e: React.FormEvent) { e.preventDefault(); const res = await fetch("/api/contact-seller", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ listingId, fromName: name, fromEmail: email, body }) }); const data = await res.json(); setNotice(data.error || data.notice || "Sent."); }
  async function save() { const res = await fetch("/api/favorites", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ listingId }) }); setNotice(res.ok ? "Saved to your account." : "Sign in to save listings."); }
  async function share() { const url = `${window.location.origin}/l/${slug}`; if (navigator.share) await navigator.share({ title, url }).catch(() => undefined); else await navigator.clipboard.writeText(url); fetch("/api/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "listing_share", meta: listingId }) }).catch(() => undefined); setNotice("Listing link copied."); }
  async function report(e: React.FormEvent) { e.preventDefault(); await fetch("/api/report", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ listingId, userId: sellerId, reason, details: body }) }); setNotice("Report received."); }
  return (<div className="mt-8 grid gap-6">{notice ? <p className="rounded-xl bg-linen px-4 py-3 text-sm font-bold">{notice}</p> : null}<div className="flex flex-wrap gap-2"><button className="focus-ring min-h-11 rounded-xl border px-4 font-bold" onClick={save} type="button">Save</button><button className="focus-ring min-h-11 rounded-xl border px-4 font-bold" onClick={share} type="button">Share</button></div><form onSubmit={contact} className="grid gap-3 rounded-2xl border border-borderwarm bg-card p-4"><h2 className="font-bold">Contact seller</h2><p className="text-sm text-muted">Meet in public. Do not send money to strangers.</p><input className="min-h-12 rounded-xl border px-3" placeholder="Your name" value={name} onChange={(e) => setName(e.target.value)} required /><input className="min-h-12 rounded-xl border px-3" type="email" placeholder="Your email" value={email} onChange={(e) => setEmail(e.target.value)} required /><textarea className="min-h-28 rounded-xl border px-3 py-2" placeholder="When can you pick this up?" value={body} onChange={(e) => setBody(e.target.value)} required /><button className="focus-ring min-h-12 rounded-xl bg-garden font-bold text-white" type="submit">Send message</button></form><form onSubmit={report} className="grid gap-3 text-sm"><h2 className="font-bold">Report listing</h2><select className="min-h-11 rounded-xl border px-3" value={reason} onChange={(e) => setReason(e.target.value)}><option value="spam">Spam or scam</option><option value="prohibited">Prohibited item</option><option value="unsafe">Unsafe or misleading</option></select><button className="focus-ring min-h-11 rounded-xl border px-4 font-bold" type="submit">Submit report</button></form></div>);
}
