"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { CATEGORIES, OFFER_TYPES } from "@/lib/catalog";
import type { PublicUser } from "@/lib/types";
export function ListingForm({ user }: { user: PublicUser }) {
  const router = useRouter(); const [error, setError] = useState(""); const [offerType, setOfferType] = useState("sell");
  async function onSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    fetch("/api/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "listing_create_start" }) }).catch(() => undefined);
    const res = await fetch("/api/listings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.get("title"), description: form.get("description"), category: form.get("category"), offerType: form.get("offerType"), price: form.get("price"), quantity: form.get("quantity"), city: form.get("city"), region: form.get("region"), postalCode: form.get("postalCode"), neighborhood: form.get("neighborhood"), pickupArea: form.get("pickupArea"), photos: String(form.get("photo") || "").trim() ? [String(form.get("photo")).trim()] : [] }) });
    const data = await res.json(); if (!res.ok) { setError(data.error || "Could not post."); return; } router.push(`/l/${data.listing.slug}`); router.refresh();
  }
  return (<form onSubmit={onSubmit} className="mt-6 grid gap-3">{error ? <p className="rounded-xl bg-linen px-3 py-2 text-sm font-bold">{error}</p> : null}<input name="title" required minLength={3} className="min-h-12 rounded-xl border px-3" placeholder="Roma tomatoes" /><textarea name="description" required minLength={8} className="min-h-28 rounded-xl border px-3 py-2" placeholder="What it is and how people can get it." /><select name="category" className="min-h-12 rounded-xl border px-3" defaultValue="produce">{CATEGORIES.map((c) => <option key={c.slug} value={c.slug}>{c.label}</option>)}</select><select name="offerType" className="min-h-12 rounded-xl border px-3" value={offerType} onChange={(e) => setOfferType(e.target.value)}>{OFFER_TYPES.map((o) => <option key={o.slug} value={o.slug}>{o.label}</option>)}</select>{offerType === "sell" ? <input name="price" type="number" min="0" step="0.01" className="min-h-12 rounded-xl border px-3" placeholder="Price" /> : null}<input name="quantity" className="min-h-12 rounded-xl border px-3" placeholder="Quantity, optional" /><input name="city" defaultValue={user.city} className="min-h-12 rounded-xl border px-3" placeholder="City" /><input name="region" defaultValue={user.region} className="min-h-12 rounded-xl border px-3" placeholder="State" /><input name="postalCode" defaultValue={user.postalCode} className="min-h-12 rounded-xl border px-3" placeholder="ZIP" /><input name="neighborhood" defaultValue={user.neighborhood} className="min-h-12 rounded-xl border px-3" placeholder="Neighborhood" /><input name="pickupArea" className="min-h-12 rounded-xl border px-3" placeholder="Pickup area, not a street address" /><input name="photo" className="min-h-12 rounded-xl border px-3" placeholder="Photo URL, optional" /><button className="focus-ring min-h-12 rounded-xl bg-garden font-bold text-white" type="submit">Publish listing</button></form>);
}
